language: c
os: 
  - osx
  - linux
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - ocl-icd-opencl-dev
install: true
script: 
  - mkdir build && cd build
  - cmake -G "Unix Makefiles" ..
  - make
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo make install; else make install; fi
  - oclinfo -pds